 [
  "MS Dhoni",
  "Ruturaj Gaikwad",
  "Shivam Dube",
  "Sanju Samson",
  "Shreyas Gopal",
  "Gurjapneet Singh",
  "Anshul Kamboj",
  "Khaleel Ahmed",
  "Ayush Mhatre",
  "Ramakrishna Ghosh",
  "Mukesh Choudhary",
  "Nathan Ellis",
  "Noor Ahmad",
  "Dewald Brevis",
  "Urvil Patel",

  "Prashant Veer",
  "Kartik Sharma",
  "Akeal Hosein",
  "Matthew Short",
  "Aman Khan",

  "KL Rahul",
  "Axar Patel",
  "Nitish Rana",
  "T Natarajan",
  "Mukesh Kumar",
  "Abhishek Porel",
  "Ajay Mandal",
  "Ashutosh Sharma",
  "Karun Nair",
  "Madhav Tiwari",
  "Sameer Rizvi",
  "Tripurana Vijay",
  "Vipraj Nigam",
  "Mitchell Starc",
  "Dushmantha Chameera",
  "Tristan Stubbs",

  "David Miller",
  "Ben Duckett",
  "Pathum Nissanka",
  "Auqib Dar",
  "Lungi Ngidi",
  "Kyle Jamieson",

  "Shubman Gill",
  "Sai Sudharsan",
  "Mohammad Siraj",
  "Jos Buttler",
  "Glenn Phillips",
  "Rashid Khan",
  "R Sai Kishore",
  "Jayant Yadav",
  "Ishant Sharma",
  "Manav Suthar",
  "Mohd Arshad Khan",
  "Prasidh Krishna",
  "Nishant Sindhu",
  "Rahul Tewatia",
  "Washington Sundar",
  "Anuj Rawat",
  "Kumar Kushagra",

  "Jason Holder",
  "Tom Banton",
  "Ashok Sharma",
  "Luke Wood",

  "Rinku Singh",
  "Manish Pandey",
  "Ajinkya Rahane",
  "Varun Chakaravarthy",
  "Umran Malik",
  "Vaibhav Arora",
  "Harshit Rana",
  "Angkrish Raghuvanshi",
  "Anukul Roy",
  "Ramandeep Singh",
  "Sunil Narine",
  "Rovman Powell",

  "Cameron Green",
  "Matheesha Pathirana",
  "Mustafizur Rahman",
  "Rachin Ravindra",
  "Finn Allen",
  "Tim Seifert",
  "Akash Deep",
  "Rahul Tripathi",
  "Tejasvi Singh",
  "Daksh Kamra",
  "Sarthak Ranjan",
  "Prashant Solanki",
  "Kartik Tyagi",


  "Arjun Tendulkar",
  "Mohammed Shami",
  "Ayush Badoni",
  "Mayank Yadav",
  "Avesh Khan",
  "Himmat Singh",
  "Digvesh Rathi",
  "Akash Singh",
  "Abdul Samad",
  "Prince Yadav",
  "Rishabh Pant",
  "Manimaran Siddharth",
  "Shahbaz Ahmed",
  "Aiden Markram",
  "Matthew Breetzke",
  "Mitchell Marsh",
  "Nicholas Pooran",

  "Josh Inglis",
  "Anrich Nortje",
  "Wanindu Hasaranga",
  "Akshat Raghuwanshi",
  "Mukul Choudhary",
  "Naman Tiwari",


  "Rohit Sharma",
  "Hardik Pandya",
  "Jasprit Bumrah",
  "Suryakumar Yadav",
  "Tilak Varma",
  "Raj Angad Bawa",
  "Deepak Chahar",
  "Shardul Thakur",
  "Mayank Markande",
  "Naman Dhir",
  "Raghu Sharma",
  "Robin Minz",
  "Shashwat Nishant",

  "Will Jacks",
  "Ryan Rickelton",
  "Corbin Bosch",
  "Allah Ghazanfar",
  "Trent Boult",
  "Sherfane Rutherford",

  "Quinton de Kock",
  "Mayank Rawat",
  "Atharva Ankolekar",
  "Mohammad Izhar",
  "Danish Malewar",

  "Shreyas Iyer",
  "Arshdeep Singh",
  "Harpreet Brar",
  "Vishnu Vinod",
  "Prabhsimran Singh",
  "Harnoor Pannu",
  "Nehal Wadhera",
  "Pyla Avinash",
  "Priyansh Arya",
  "Shashank Singh",
  "Suryansh Shedge",
  "Vyshak Vijaykumar",
  "Yash Thakur",

  "Marco Jansen",
  "Lockie Ferguson",
  "Marcus Stoinis",
  "Azmatullah Omarzai",
  "Mitch Owen",
  "Xavier Bartlett",

  "Cooper Connolly",
  "Ben Dwarshuis",
  "Vishal Nishad",
  "Pravin Dubey",

  
  "Yashaswi Jaiswal",
  "Ravindra Jadeja",
  "Riyan Parag",
  "Sandeep Sharma",
  "Tushar Deshpande",
  "Vaibhav Suryavanshi",
  "Yudhvir Charak",
  "Dhruv Jurel",

  "Jofra Archer",
  "Sam Curran",
  "Shimron Hetmyer",
  "Nandre Burger",
  "Lhuan-Dre Pretorius",
  "Kwena Maphaka",

  "Ravi Bishnoi",
  "Adam Milne",
  "Kuldeep Sen",
  "Ravi Singh",
  "Sushant Mishra",
  "Brijesh Sharma",
  "Aman Rao Perala",
  "Vignesh Puthur",
  "Yash Raj Punja",


  "Virat Kohli",
  "Devdutt Padikkal",
  "Rajat Patidar",
  "Yash Dayal",
  "Jitesh Sharma",
  "Swapnil Singh",
  "Rasikh Dar",
  "Abhinandan Singh",

  "Tim David",
  "Josh Hazlewood",
  "Phil Salt",
  "Romario Shepherd",
  "Nuwan Thushara",

  "Venkatesh Iyer",
  "Jacob Duffy",
  "Jordan Cox",
  "Mangesh Yadav",
  "Kanishk Chouhan",
  "Vihaan Malhotra",
  "Vicky Ostwal",
  "Satvik Deswal",

  "Abhishek Sharma",
  "Ishan Kishan",
  "Jaydev Unadkat",
  "Nitish Kumar Reddy",
  "Harshal Patel",
  "Zeeshan Ansari",
  "Harsh Dubey",
  "Smaran Ravichandaran",

  "Pat Cummins",
  "Heinrich Klaasen",
  "Kamindu Mendis",
  "Brydon Carse",
  "Travis Head",

  "Liam Livingstone",
  "Jack Edwards",
  "Shivam Mavi",
  "Salil Arora",
  "Krains Fuletra",
  "Praful Hinge",
  "Amit Kumar",
  "Onkar Tarmale",
  "Sakib Hussain",
  "Shivang Kumar"

]